### ISSUE TITLE
Are tests supposed to pass?

### ISSUE THREAD

**Issue by metaproph3t** [raydium-io/raydium-clmm#64]
When I run `cargo test-sbf` on my local machine, I see the following:
```
---- states::pool::pool_test::use_tickarray_bitmap_extension_test::get_first_initialized_tick_array_test stdout ----
thread 'states::pool::pool_test::use_tickarray_bitmap_extension_test::get_first_initialized_tick_array_test' panicked at programs/amm/src/states/pool.rs:177:69:
called `Result::unwrap()` on an `Err` value: InvalidSeeds

---- states::pool::pool_test::use_tickarray_bitmap_extension_test::next_initialized_tick_array_start_index_test::from_extension_positive_bitmap_to_extension_negative_bitmap stdout ----
thread 'states::pool::pool_test::use_tickarray_bitmap_extension_test::next_initialized_tick_array_start_index_test::from_extension_positive_bitmap_to_extension_negative_bitmap' panicked at programs/amm/src/states/pool.rs:177:69:
called `Result::unwrap()` on an `Err` value: InvalidSeeds

---- states::pool::pool_test::use_tickarray_bitmap_extension_test::next_initialized_tick_array_start_index_test::from_extension_negative_bitmap_to_extension_positive_bitmap stdout ----
thread 'states::pool::pool_test::use_tickarray_bitmap_extension_test::next_initialized_tick_array_start_index_test::from_extension_negative_bitmap_to_extension_positive_bitmap' panicked at programs/amm/src/states/pool.rs:177:69:
called `Result::unwrap()` on an `Err` value: InvalidSeeds

---- states::pool::pool_test::use_tickarray_bitmap_extension_test::next_initialized_tick_array_start_index_test::from_pool_bitmap_to_extension_positive_bitmap stdout ----
thread 'states::pool::pool_test::use_tickarray_bitmap_extension_test::next_initialized_tick_array_start_index_test::from_pool_bitmap_to_extension_positive_bitmap' panicked at programs/amm/src/states/pool.rs:177:69:
called `Result::unwrap()` on an `Err` value: InvalidSeeds

---- states::pool::pool_test::use_tickarray_bitmap_extension_test::next_initialized_tick_array_start_index_test::min_tick_max_tick_initialized_test stdout ----
thread 'states::pool::pool_test::use_tickarray_bitmap_extension_test::next_initialized_tick_array_start_index_test::min_tick_max_tick_initialized_test' panicked at programs/amm/src/states/pool.rs:177:69:
called `Result::unwrap()` on an `Err` value: InvalidSeeds

---- states::pool::pool_test::use_tickarray_bitmap_extension_test::next_initialized_tick_array_start_index_test::from_pool_bitmap_to_extension_negative_bitmap stdout ----
thread 'states::pool::pool_test::use_tickarray_bitmap_extension_test::next_initialized_tick_array_start_index_test::from_pool_bitmap_to_extension_negative_bitmap' panicked at programs/amm/src/states/pool.rs:177:69:
called `Result::unwrap()` on an `Err` value: InvalidSeeds
```

Am I doing something wrong? I've tried Solana version 0.16.17 and 0.18.4.

**Comment by weirdgiraffe** [comment]
Added PR to fix them https://github.com/raydium-io/raydium-clmm/pull/67

**Comment by RainRaydium** [comment]
Thanks for your issue.
All the tests have been passed in the new version.
